import marimo

__generated_with = "0.20.2"
app = marimo.App(width="medium", app_title="Visualize delta results")

with app.setup(hide_code=True):
    import marimo as mo
    import uuid

    # Custom from within the project
    from helper.core_models import DatasetRegistry, PlotConfig, AppState
    from helper.discovery import load_dataset
    from helper.grouping import create_group

    from helper.plotting.plot_dispatcher import plot_group

    # Some global states
    get_groups, set_groups = mo.state({})
    registry=DatasetRegistry()


@app.cell(hide_code=True)
def _():
    csv_file_browser = mo.ui.file_browser(
        label="Select the benchmarks you want to compare",
        filetypes=["csv"],
        selection_mode="file",
        multiple=True,
    ).form()

    # TODO: render all the ui in a vstack and move the logic into another column / cell so it is way cleaner
    csv_file_browser
    return (csv_file_browser,)


@app.cell(hide_code=True)
def _(csv_file_browser):
    warnings = []
    datasets = []

    if (
        csv_file_browser.value is None
        or csv_file_browser.value == ()
        or csv_file_browser.value[0].path == ()
    ):
        warnings.append("No files selected.")
    else:
        for csv in csv_file_browser.value:
            try:
                ds = load_dataset(csv.path)
                datasets.append(ds)
            except ValueError as e:
                warnings.append(
                    f"The selected csv file '{csv.name}' is not a file generated by delta."
                )
                warnings.append(str(e))
    return datasets, warnings


@app.cell(hide_code=True)
def _(warnings):
    if warnings:
        warning_str = "CSV data could not be loaded:\n\n" + "\n".join(
            f"- {w}" for w in warnings
        )
        output = mo.callout(
            mo.plain_text(warning_str),
            kind="warn",
        )
    else:
        output = mo.callout(
            "Successfully loaded benchmark data",
            kind="success",
        )

    output
    return


@app.cell(hide_code=True)
def _(datasets):
    for set in datasets:
        try:
            registry.add(set)
        except ValueError as e:
            # TODO: use callout here
            print(str(e))
    return


@app.cell(hide_code=True)
def _(datasets):
    options = {f"{ds.display_name} ({ds.type})": ds.id for ds in datasets}
    _label_identifier = "Dataset name"

    group_name_input = mo.ui.text(label="Groupname")
    dataset_table_input = mo.ui.table(
        data=[{_label_identifier: name} for name in options.keys()],
        selection="multi",
        label="Select datasets"
    )

    def handle_create_group(form_value):
        if not form_value or not form_value["name"]:
            return
        if any(g.name == form_value["name"] for g in get_groups().values()):
            return

        selected_names = [row[_label_identifier] for row in form_value["datasets"]]
        selected_ids = [options[name] for name in selected_names]

        new_group = create_group(registry, form_value["name"], selected_ids)
        group_id = getattr(new_group, 'id', str(uuid.uuid4()))
        set_groups({**get_groups(), group_id: new_group})


    return dataset_table_input, group_name_input, handle_create_group


@app.cell(hide_code=True)
def _():
    # Diese Zelle wird automatisch neu ausgeführt, wenn set_groups() gerufen wird!
    current_groups_list = [
        {"ID": g_id, "Name": g.name, "Datasets": len(g.dataset_ids)} 
        for g_id, g in get_groups().items()
    ]

    groups_mgmt_table = mo.ui.table(
        data=current_groups_list,
        selection="multi",
        label="Existing Groups"
    )
    return (groups_mgmt_table,)


@app.cell(hide_code=True)
def _(
    dataset_table_input,
    group_name_input,
    groups_mgmt_table,
    handle_create_group,
):
    clear_btn = mo.ui.button(
        label="Clear all", 
        on_click=lambda _:set_groups({}), 
        kind="danger"
    )

    delete_btn = mo.ui.button(
        label="Delete selected", 
        on_click=lambda _: set_groups({
            k: v for k, v in get_groups().items() 
            if k not in {row["ID"] for row in (groups_mgmt_table.value or [])}
        }),
        kind="neutral"
    )

    creation_section = (
        mo.md("{name}\n{datasets}")
        .batch(name=group_name_input, datasets=dataset_table_input)
        .form(
            submit_button_label="Add Group to List",
            on_change=handle_create_group,
            bordered=False
        )
    )

    mo.vstack([
        mo.md("### Create plot groups"),
        creation_section,
        mo.md("---"),
        mo.md("### Manage Existing Groups"),
        groups_mgmt_table,
        mo.hstack([delete_btn, clear_btn], justify="start"),
    ])
    return


@app.cell(hide_code=True)
def _():
    color_map_editor = mo.ui.data_editor(
        data=[{"Column Identifier": "", "Color (Hex)": ""}],
        label="Color Overrides",
    )

    label_map_editor = mo.ui.data_editor(
        data=[{"Column Identifier": "", "Legend Label": ""}],
        label="Label Overrides",
    )

    config_form = (
        mo.md("""
        ### Setup the plot configuration

        {memory_metric}

        {memory_unit}

        {timeline_alignment}

        {y_scale}

        ### Set colorpalette
        {color_map}

        ### Set labelmap
        {label_map}

        ### Select a directory to save the plots to (optional)
        {save_dir}
        """)
        .batch(
            memory_metric=mo.ui.dropdown(
                label="Memory metric",
                options=["physical", "virtual"],
                value="physical",
            ),
            memory_unit=mo.ui.dropdown(
                label="Memory unit",
                options=["mb", "bytes"],
                value="mb"
            ),
            timeline_alignment=mo.ui.dropdown(
                label="Timeline alignment",
                options=["truncate", "interpolate", "per_run"],
                value="truncate",
            ),
            y_scale=mo.ui.dropdown(
                label="Y scale",
                options=["linear", "log"],
                value="linear",
            ),
            # TODO: use the data editor here
            color_map=color_map_editor,
            label_map=label_map_editor,
            save_dir=mo.ui.file_browser(
                multiple=False,
                selection_mode="directory",
            ),
        )
        .form(
            show_clear_button=True,
            bordered=True,
            submit_button_label="Set Configuration",
        )
    )

    config_form
    return (config_form,)


@app.cell
def _(config_form):
    config = None

    if config_form.value:
        def list_to_dict(table_data, key_col="Key", val_col="Value"):
            return {
                row[key_col]: row[val_col] 
                for row in table_data 
                if row.get(key_col) and str(row[key_col]).strip() != ""
            }

        config = PlotConfig(
            memory_metric=config_form.value["memory_metric"],
            memory_unit=config_form.value["memory_unit"],
            timeline_alignment=config_form.value["timeline_alignment"],
            y_scale=config_form.value["y_scale"],
            palette=list_to_dict(
                config_form.value["color_map"], 
                key_col="Column Identifier", 
                val_col="Color (Hex)"
            ),
            label_map=list_to_dict(
                config_form.value["label_map"], 
                key_col="Column Identifier", 
                val_col="Legend Label"
            ),
        )

    app_state = AppState(registry=registry, groups=get_groups(), config=config)
    return (app_state,)


@app.cell
def _(app_state):
    plots = app_state.plot_all()

    if len(plots) == 1:
        mo.output.append(plots)
    elif len(plots) > 1:
        mo.output.append(mo.carousel(plots))
    else:
        mo.output.append(mo.callout("Nothing to plot", kind="info"))
    
    AppState.close_all_plots(plots)
    return


if __name__ == "__main__":
    app.run()
