import marimo

__generated_with = "0.20.2"
app = marimo.App(
    width="medium",
    app_title="Visualize delta results",
    layout_file="layouts/visualize.grid.json",
)

with app.setup(hide_code=True):
    import marimo as mo

    # Custom from within the project
    from helper.core_models import Dataset, DatasetRegistry, Group, PlotConfig, AppState
    from helper.discovery import detect_dataset_type, discover_csv_files, load_dataset
    from helper.grouping import create_group

    from helper.plotting.plot_dispatcher import plot_group
    from helper.plotting.plot_memory_max import plot_memory_max_group
    from helper.plotting.plot_memory_timeline import plot_memory_timeline_group
    from helper.plotting.plot_time import plot_time_group
    from helper.plotting.plotting_utils import convert_duration, bytes_to_mb


@app.cell(hide_code=True)
def _():
    csv_file_browser = mo.ui.file_browser(
        label="Select the benchmarks zou want to compare",
        filetypes=["csv"],
        selection_mode="file",
        multiple=True,
    ).form()

    # TODO: render all the ui in a vstack and move the logic into another column / cell so it is way cleaner
    csv_file_browser
    return (csv_file_browser,)


@app.cell(hide_code=True)
def _(csv_file_browser):
    warnings = []
    datasets = []

    if (
        csv_file_browser.value is None
        or csv_file_browser.value == ()
        or csv_file_browser.value[0].path == ()
    ):
        warnings.append("No files selected.")
    else:
        for csv in csv_file_browser.value:
            try:
                ds = load_dataset(csv.path)
                datasets.append(ds)
            except ValueError as e:
                warnings.append(f"The selected csv file '{csv.name}' is not a file generated by delta.")
                warnings.append(str(e))
    return datasets, warnings


@app.cell(hide_code=True)
def _(warnings):
    if warnings:
        warning_str = "CSV data could not be loaded:\n\n" + "\n".join(
            f"- {w}" for w in warnings
        )
        output = mo.callout(
            mo.plain_text(warning_str),
            kind="warn",
        )
    else:
        output = mo.callout(
            "Successfully loaded benchmark data",
            kind="success",
        )

    output
    return


@app.cell(hide_code=True)
def _(datasets):
    registry = DatasetRegistry()
    for set in datasets:
        try:
            registry.add(set)
        except ValueError as e:
            print(str(e))
    return (registry,)


@app.cell
def _(datasets):
    options = {
        f"{ds.display_name} ({ds.type})": ds.id
        for ds in datasets
    }

    # TODO: make it possible to createe multiple at once
    group_creation_form = ( 
        mo.md('''
        **Create plot groups.**

        {name}

        {datasets}
        ''')
        .batch(
            name=mo.ui.text(label="Groupname"),
            datasets=mo.ui.multiselect(label="Select datasets for group", options=options),
        )
        .form(
            show_clear_button=True,
            bordered=True,
            submit_button_label="Create Group"
        )
    )

    group_creation_form
    return (group_creation_form,)


@app.cell
def _(group_creation_form, registry):
    group = None
    error = None

    if group_creation_form.value:
        try:
            group = create_group(
                registry,
                group_creation_form.value["name"],
                group_creation_form.value["datasets"],
            )
        except ValueError as e:
            error = str(e)
    return (group,)


@app.cell
def _():
    # TODO: support all config options and not just these
    config_form = ( 
        mo.md('''
        **Setup the plot configuration**

        {memory_metric}

        {memory_unit}

        {timeline_alignment}
    
        {y_scale}
        ''')
        .batch(
            memory_metric = mo.ui.dropdown(
                label="Memory metric",
                options=["physical", "virtual"],
                value="physical",
            ),
            memory_unit = mo.ui.dropdown(
                label="Memory unit",
                options=["mb", "bytes"],
                value="mb",
            ),
            timeline_alignment = mo.ui.dropdown(
                label="Timeline alignment",
                options=["truncate", "interpolate", "per_run"],
                value="truncate",
            ),
            y_scale = mo.ui.dropdown(
                label="Y scale",
                options=["linear", "log"],
                value="linear",
            )
        )
        .form(
            show_clear_button=True,
            bordered=True,
            submit_button_label="Set Configuration"
        )
    )

    config_form
    return (config_form,)


@app.cell
def _(config_form):
    config = None

    if config_form.value:
        config = PlotConfig(
            memory_metric=config_form.value["memory_metric"],
            memory_unit=config_form.value["memory_unit"],
            timeline_alignment=config_form.value["timeline_alignment"],
            y_scale=config_form.value["y_scale"],
        )
    return (config,)


@app.cell
def _(config, group, registry):
    if group is None:
        final_output = mo.callout("No group created.", kind="warn")
    if config is None:
        final_output = mo.callout("No plot configuration set", kind="warn")

    if group is not None and config is not None:
        try:
            final_output = plot_group(group, registry, config)
        except Exception as e:
            final_output = mo.callout(str(e), kind="warn")

    final_output
    return


if __name__ == "__main__":
    app.run()
